#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.15

pipelines:
  default:
    - parallel:
      - step:
          name: Lint code
          image: golangci/golangci-lint:v1.31.0
          script:
            - golangci-lint run -v
      - step:
          name: Test and Build
          script:
            # - mkdir test-reports
            # - go get -u github.com/jstemmer/go-junit-report
            # - go test tests/* -v 2>&1 | go-junit-report > test-reports/report.xml
            # Build compiles the packages
            - mkdir ./build
            - go version
            - go mod tidy
            - go build -a -v -o ./build/ .
            - curl -X POST --user "${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./build/projector"
